---

# install tasks for apt based hosts

- name: install common packages (apt)
  apt:
    name: "{{ item.name | default(item) }}"
    install_recommends: "{{ package_recommends }}"
    state: "{{ package_state }}"
    purge: "{{ package_purge }}"
    default_release: "{{ package_release }}"
  with_flattened:
    - common_packages_all
    - common_packages_apt_all
    - common_packages_group
    - common_packages_apt_group
    - common_packages_host
    - common_packages_apt_host
